# Generated by Django 5.0.7 on 2024-08-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tg_id',
            new_name='id',
        ),
    ]
