# Generated by Django 4.2.4 on 2024-08-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='UNALTERED', max_length=128),
        ),
    ]
